# This is a basic workflow to help you get started with the CI/CD for Functions Project

name: Build and Deploy Job

# Controls when the workflow will run
on:
  # Triggers the workflow on push event but only for the "main" branch
  push:
    branches: [main]

  pull_request: 
    branches: [develop]
    types: [closed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      # Description: Your function app name on Azure
      # TODO : Replace <function_app_name> with the name of your function app
      AZURE_FUNCTIONAPP_NAME: my-first-function-20231021072333796
      # Description: The directory which contains pom.xml file
      POM_XML_DIRECTORY: '.'
      # Description: The function app name in your local development.
      # TODO : Replace <pom_function_app_name> with the name of task. This can be found in your function's pom.xml, under the *'functionAppName'* tag under properties.
      POM_FUNCTIONAPP_NAME: my-first-function-20231021072333796
      # Description: The java version to use
      JAVA_VERSION: '1.8.x'

    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Azure CLI
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: Setup Java
          uses: actions/setup-java@v1
          with:
            java-version: ${{ env.JAVA_VERSION }}

        - name: 'Restore Project Dependencies Using Mvn'
          shell: pwsh
          run: |
            pushd './${{ env.POM_XML_DIRECTORY }}'
            mvn clean package
            mvn azure-functions:package
            popd

        - name: 'Run Azure Functions Action'
          uses: Azure/functions-action@v1
          with:
            # Description: Name of the Azure Function App
            app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
            # Description: Path to package or folder. \*.zip or a folder to deploy
            package: './${{ env.POM_XML_DIRECTORY }}/target/azure-functions/${{ env.POM_FUNCTIONAPP_NAME }}'
            # Description: Publish profile (\*.publishsettings) file contents with web deploy secrets
            publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_STAGING_PUBLISH_PROFILE }}

          
