on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  # This workflow contains a single job called "swap-function"
  swap-function:
    # The swap action can only be triggered when a pull request is from develop branch
    if: ${{ github.head_ref == 'develop' }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Swap the Azure Function'
        run: |
          az functionapp deployment slot swap -g java-functions-group -n my-first-function-20231021072333796 --slot staging --target-slot production